INSERT INTO banks (bank_code, bank_name) VALUES
('BTRL', 'Banca Transilvania'),
('RNCB', 'Banca Comercială Română (BCR)'),
('BACX', 'UniCredit Bank'),
('CECE', 'CEC Bank'),
('BRDE', 'BRD - Groupe Société Générale'),
('RZBR', 'Raiffeisen Bank'),
('INGB', 'ING Bank'),
('OTPV', 'OTP Bank'),
('WBAN', 'Intesa Sanpaolo Bank'),
('UGBI', 'Garanti BBVA'),
('BREL', 'Libra Internet Bank'),
('CARP', 'Patria Bank'),
('EXIM', 'Eximbank'),
('FNNB', 'Credit Europe Bank'),
('CRCO', 'Banca Centrală Cooperatistă Creditcoop'),
('MIRO', 'ProCredit Bank'),
('REVO', 'Revolut România'),
('TREZ', 'Trezoreria Statului'),
('ABNA', 'ABN Amro Bank'),
('BUCU', 'Alpha Bank România'),
('BPOS', 'Banc Post'),
('BSEA', 'Banca Comercială a Greciei'),
('CBIT', 'Banca Comercială Ion Țiriac'),
('BNRB', 'Banca Comercială Robank'),
('CRDZ', 'Banca de Credit și Dezvoltare Romexterra'),
('BROM', 'Banca di Roma'),
('BITR', 'Banca Italo-Romena'),
('ETHN', 'Banca Națională a Greciei'),
('NBOR', 'Banca Națională a României'),
('BRMA', 'Banca Românească'),
('BFRO', 'Banque Franco Roumaine'),
('CITI', 'Citibank'),
('DARO', 'Daewoo Bank'),
('EGNA', 'Egnatia Bank'),
('DAFB', 'Eurom Bank'),
('FRBU', 'Frankfurt Bukarest Bank'),
('MIND', 'MindBank'),
('MIRB', 'Misr Bank'),
('BCUN', 'Nova Bank'),
('PIRB', 'Piraeus Bank'),
('ROIN', 'Romanian International Bank'),
('UNCR', 'UniCredit România'),
('VBBU', 'Volksbank România')
ON CONFLICT (bank_code) DO NOTHING;