INSERT INTO banks (bank_code, bank_name) VALUES
('BTRL', 'Banca Transilvania'),
('RNCB', 'Banca Comercială Română (BCR)'),
('BACX', 'UniCredit Bank'),
('CECE', 'CEC Bank'),
('BRDE', 'BRD - Groupe Société Générale'),
('RZBR', 'Raiffeisen Bank'),
('INGB', 'ING Bank'),
('OTPV', 'OTP Bank'),
('WBAN', 'Intesa Sanpaolo Bank'),
('UGBI', 'Garanti BBVA'),
('BREL', 'Libra Internet Bank'),
('CARP', 'Patria Bank'),
('EXIM', 'Eximbank'),
('FNNB', 'Credit Europe Bank'),
('CRCO', 'Banca Centrală Cooperatistă Creditcoop'),
('MIRO', 'ProCredit Bank'),
('REVO', 'Revolut România'),
('TREZ', 'Trezoreria Statului');